name: simple_cmms_demo
description: This is Simple CMMS Demo for Emaintec.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: "^0.7.2+1"
  http: 0.12.0+2
  path_provider: ^1.3.0
  image_picker: ^0.6.1+4

flutter_icons:
  image_path: "assets/icons/app_icon_512.png"
  android: true
  ios: true

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
